sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: W94aRO5KnjiIC+R3cCPVcOU3JAofyl8sOO235ruQ1Cu5Wd06aosFv2zTFD91RuL4vKz0h4blAY9wmzTz2O0/poOuNbiN+Di4wyUPOdQ5bF1TstW+ZX/NKKB7U+wh4QMZbIUvpwyrHXYPUawBz8W48l9vq6fGO/haVH18daPWJxFHWL/YAigTvmhm3F68xYHyUkuCsfAUXSfrXMR3FOVr7rMRN3TZ6l2S0Iz7pf+9o6UDFrZ2khKb/7l7zXF/p620aZ8OqU+EWQNg7SwF908bfqg9/P/nQ+JBqhoVwp1SBDcjE64iKjFUM6/6BTGasBbhw/CYWc3oAiQbPgFRFPfhCo+Rw+3EINeCstGSMiSUnh9j+WfJk4Zn6LYdQA8WVeKouUSuu7iNAwOy7GYktxUEi7e+szGbFknM1MOuLiub7CuuNXNQCGRxvqQgnKTMWQa6884wdLgxrUyKXNpVplX/irDy+RgIhtUuDU4AvZgK9kvS8K8rCORKCaECAToKGdkXPBoxKEs6AU7Rzi73pST4Q+2yYcCuBRhZgwSx1zUbb+rPDt2w+BCCJlNfFoy7w2KFigt1OQlJ4WhsYZb2l002lrpchD9Oe7F2e5ymwTjxgJ7QiXhJDPEEcz2ki6RdgOM/zZXNr0AN857sGC8rUM92W5zJoqA2vM/NxsSQmULbVZ8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Song-Book-of-Quong-Lee-of-Limehouse_2161
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy